### ISSUE TITLE
Release v2.1 (Feb 17, 2020) CBOR Tags and Duplicate Map Key Options

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#118]
UPDATED (Feb. 17, 17:00 CST)

It's all done except release notes and tagging!

Progress:  

- [x] #44 - Add support for CBOR tags (major type 6)
- [x] #147 - Decode "keyasint" structs faster and with less memory
- [x] #125 - Add encoding option to tag or not tag time values
- [x] #47 - Improve decoding speed (optimizations already identified during v1)
- [x] Cleanup and fix reported lint issues for #44, #47, #125, #147 changes
- [x] Basic optimization for CBOR tags feature, more can be done in later releases
- [x] Decided to combine v2.1 and v2.2 to reduce overhead (fuzzing, docs, benchmarks, charts, etc.)
- [x] Decided (Un)MarshalerWithMode isn't needed in v2.1.
- [x] Get feedback on proposed v2.1 API and decide what features to add/modify/remove. See #136. 
  - [x] Will add EncModeWithSharedTags (there will be 3 funcs to create EncMode, see table below)
  - [x] Will make sure EncMode, DecMode, and TagSet can be initialized before init() 
- [x] #151 - Implement default encoding for uninitialized time.Time values when tag-required option is specified.

The above has been pushed to tip.  The remaining items will be in a new PR.

- [x] #122 - Add decoding options for duplicate map keys
- [x] Cleanup and fix reported lint issues for #122 changes
- [x] Begin fuzzing for release tag (it won't be restarted for changes limited to docs or tests)
- [x] Update README.md and benchmarks

There will be three ways to create EncMode (all are reusable and concurrency safe interface.)

|Function (returns EncMode)                | Encoding Mode                                                                |
|---------------------------------------------------|------------------------------------------------------------------------------|
|EncOptions{...}.EncMode() | immutable options, no tags
|:new: EncOptions{...}.EncModeWithTags(ts) | both options & tags are immutable
|:new: EncOptions{...}.EncModeWithSharedTags(ts) | immutable options & mutable shared tags |

To minimize bloat, only tags 0 and 1 (datetime) are going to be part of the default build.  The API provides a way for users to register and handle other CBOR tags for user-defined Go types.

In future releases, additional tags may be provided by the library in a modular way (possibly build flags or optional packages).

**Comment by fxamacker** [comment]
I got both #44 and #125 done with new code 100% covered by tests, but it's slower than I'd like.  I'm going to improve performance before pushing to GitHub.

**Comment by x448** [comment]
@fxamacker nice work on on optimizing after your last comment.  I updated progress.

**Comment by fxamacker** [comment]
I'm combining v2.1 and v2.2 with goal of releasing this weekend.  So we'll have these in v2.1:
* CBOR tags (finished)
* Options for duplicate map keys
* Optimizations for faster speed & fewer allocs

**Comment by x448** [comment]
Here's some performance info mentioned #149 on Feb 13, 2020.

Improved decoding speed and memory for "keyasint" struct (COSE, CWT, etc.):

* speed is faster by 24% - 28%.
* memory allocs is reduced by 44% - 61%.
* memory bytes is reduced by 13% - 26%.

Encoding is slower by 2% - 4% because of added features.  Optimization of encoding can be tackled in future releases because it is still very fast.

When COSE and CWT is decoded with option to enforce unique duplicate map keys (coming soon), then using that option will eat into some of the above gains.

**Comment by fxamacker** [comment]
Started fuzzing for v2.1 and will let it run overnight.

Fuzzing won't be restarted if changes before release are limited to *.md, doc.go, example_test.go.

**Comment by x448** [comment]
Fuzzing reached 342+ million execs for @fxamacker so the code is ready for release, but README.md and doc.go need to document new features a bit more before tagging release v2.1.

**Comment by fxamacker** [comment]
v2.1 is released!   https://github.com/fxamacker/cbor/releases

I added the following special thanks to the release notes and also in README.md.

__Special Thanks__

@x448 for helping with v2.1 API, docs, and providing the general idea for DupMapKeyEnforcedAPF.
@kostko for providing feedback on the draft v2.1 API for CBOR tags.
@laurencelundblade for providing feedback to @x448 regarding CBOR Null & Undef interop with JSON when encoding zero-instant time values.
@ZenGround0 for using this library in go-filecoin and requesting a useful feature that'll be in v2.2.
