### ISSUE TITLE
Release v2.2 (Feb 23-24)

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#126]
v2.2 will be a small release focused on a user-requested feature, replacing some hard-coded limits with options, improving docs, and bug fix for a long-standing issue detected by the updated famacker/cbor-fuzz this weekend.

Progress (some completed items might not be on GitHub yet):

- [x] Add CBOR BSTR decoding to Go byte array (Go byte slice was already supported).  #133 
- [x] Fix potential error decoding shorter CBOR indef length array to Go array (slices are OK). #170 
- [x] Update fxamacker/cbor-fuzz project and fuzz-test CBOR BSTR and Go array funcs.
- [x] Add more encoding and decoding options. #155 
- [x] Improve preset options for CTAP2. #167 
- [x] Begin fuzzing required for release tag.
- [x] Fix any issues discovered by fuzz tests before release.
- [x] Improve README, especially "Quick Start" (thanks @x448!)
- [ ] Update doc.go overview section with v2.1 and v2.2 features.
- [x] Update README for v2.2 (Current Status, comparisons, links to updated images, etc.)
- [x] Release notes

__doc.go__: The time available to work on updating doc.go was eaten up by go.dev bugs. But we managed to release on Feb 24 (about 5 minutes before minute Central Time).

Issue on golang/go for go.dev: golang/go#37284
Issue on golang/go for go.dev: golang/go#37394

v2.2 is about 1.5% ± 1% faster than v2.1, depending on benchmark (Go 1.12).

After v2.2. is released and after go.dev compatibility issues are resolved, I'd like to help open source projects migrate to v2.2 from v1.x or from other CBOR libraries.

**Comment by fxamacker** [comment]
Options for duplicate map keys has been moved to milestone v2.1.

**Comment by fxamacker** [comment]
Starting fuzzing for release v2.2.  

I reduced the scope of v2.2 so it could be released sooner, because an updated fxamacker/cbor found a bug (#170) this weekend.

Fuzzing won't be restarted if changes are limited to docs (doc.go,  example_test.go, README.md).

**Comment by fxamacker** [comment]
There's a lot of markdown tables remaining that still don't render properly on go.dev.  The tables in the intro section were converted to SVG and the rest will also be converted eventually.
